version: '2'

services:
    compression:
        build:
            context: ../  # Root of the repo - for dockerfile to find stuff.
            dockerfile: docker_container/Dockerfile
        command: sleep 3600
        image: golang
        volumes:
            - ../:/opt/src/compress
            - /mnt/logs/:/mnt/logs/
        links:
            - mongo:mongo
        environment:
            - GOPATH=/go:/opt
        working_dir: /opt/src/compress/
        privileged: true
        container_name: compression
    mongo:
        image: mongo:3.0
        command: mongod --smallfiles --nojournal --noprealloc --dbpath /mongodb/data
        tmpfs:
            - /mongodb/data:size=600M
        expose:
            - 27017
        # Suppress logging as it reduces tests duration
        logging:
            driver: none
        container_name: mongo
